### PR TITLE
Remove "back-end" specific mentions - expand to include front-end example

### PR DESCRIPTION
**Pull request by thecapacity**
I'm not sure why it shows the full list as a diff in previous changes... I just think the word "back end" is misleading since we use a lot of best practices and methods for front-end solutions too (e.g. reactive web design for browsers).

### CODE REVIEW

**Comment by brethauer** [comment]
Makes sense and looks good to me.  @wslack comments?

**Comment by wslack** [comment]
I think there are other things that can be added but am ok with this stuff. As long as this don't break any of the site URLs (do we need to update the config as well?). I also don't know what "best practices for responsive display" means - @thecapacity, can you update with more detail?

**Comment by thecapacity** [comment]
Suggest editing bullet to include " ... , reusing the best practices of existing style libraries and modern web design, to help support government product teams in creating beautiful and easy-to-use online experiences for the American people."

Language from US Web Design Standards: https://github.com/18F/web-design-standards

Might also want to mention: Responsive Web Design is increasingly important to support the growth in mobile platforms and a diverse browser ecosystem (1) along with best practices for government websites (2) and in general providing an optimal viewing and interaction experience(3) vs. designing for a specific platform.

*Citations:
1 https://pulse.cio.gov/
2 https://analytics.usa.gov/
3 https://en.wikipedia.org/wiki/Responsive_web_design

**Comment by wslack** [comment]
Will edit the other stuff in directly.

**Pull request merged**
